name: Build and Push Docker Image to CR

on:
  workflow_call:
    inputs:
      tag:
        description: 'Tag for the Docker image'
        required: true
        type: string
      cr-namespace-repository:
        description: 'Container registry namespace/repository'
        required: true
        type: string

jobs:
  build-push-cr:
    runs-on: windows-2022

    permissions:
      packages: write

    defaults:
      run:
        working-directory: Samples/PublicSamples/RecordingBot

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Tag docker image
        shell: bash
        run: |
          docker build -f ./build/Dockerfile . -t ${{ inputs.cr-namespace-repository }}:${{ inputs.tag }}

      - name: Push docker image to CR
        shell: bash
        run: |
          docker push ${{ inputs.cr-namespace-repository }}:${{ inputs.tag }}