name: Routine - Build Image

on:
  workflow_call:
    inputs:
      tag:
        description: 'Tag for the Docker image'
        required: false
        default: ''
        type: string
      cr-namespace-repository:
        description: 'Container registry namespace/repository'
        required: true
        type: string
    outputs:
      image-tag:
        description: 'Tag of the built Docker image'
        value: ${{ jobs.build-push-cr.outputs.image-tag }}
jobs:
  build-push-cr:
    runs-on: windows-2022

    permissions:
      packages: write

    defaults:
      run:
        working-directory: Samples/PublicSamples/RecordingBot

    outputs:
      image-tag: ${{ steps.generate-tag.outputs.tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Generate Docker image tag
        id: generate-tag
        shell: bash
        run: |
          if [[ -z "${{ inputs.tag }}" ]]; then
            echo "No tag provided, generating a hash based tag."
            hash=$(find ./src ./build ./scripts -type f -exec sha256sum {} \; | sort | sha256sum | awk '{print $1}')
            echo "tag=$hash" >> $GITHUB_OUTPUT
          else
            echo "Using provided tag: ${{ inputs.tag }}"
            echo "tag=${{ inputs.tag }}" >> $GITHUB_OUTPUT
          fi

      - name: Check if Docker image exists
        id: check-image
        shell: bash
        run: |
          if docker manifest inspect ${{ inputs.cr-namespace-repository }}:${{ steps.generate-tag.outputs.tag }} > /dev/null 2>&1; then
            echo "Image already exists, skipping build."
            echo "image-exists=true" >> $GITHUB_OUTPUT
          else
            echo "image-exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Build and Tag docker image
        if: steps.check-image.outputs.image-exists != 'true'
        shell: bash
        run: |
          docker build -f ./build/Dockerfile . -t ${{ inputs.cr-namespace-repository }}:${{ steps.generate-tag.outputs.tag }}

      - name: Push docker image to CR
        if: steps.check-image.outputs.image-exists != 'true'
        shell: bash
        run: |
          docker push ${{ inputs.cr-namespace-repository }}:${{ steps.generate-tag.outputs.tag }}